In [187]:
import pandas as pd

In [188]:
# usamos la base de SpaceX
df = pd.read_csv('./SpaceX_data.csv')

df = df[['rocket', 'payloads', 'launchpad', 'cores', 'flight_number', 'date_utc']]

df.head()

,rocket,payloads,launchpad,cores,flight_number,date_utc
0,5e9d0d95eda69955f709d1eb,['5eb0e4b5b6c3bb0006eeb1e1'],5e9e4502f5090995de566f86,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",1,2006-03-24T22:30:00.000Z
1,5e9d0d95eda69955f709d1eb,['5eb0e4b6b6c3bb0006eeb1e2'],5e9e4502f5090995de566f86,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",2,2007-03-21T01:10:00.000Z
2,5e9d0d95eda69955f709d1eb,"['5eb0e4b6b6c3bb0006eeb1e3', '5eb0e4b6b6c3bb00...",5e9e4502f5090995de566f86,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",3,2008-08-03T03:34:00.000Z
3,5e9d0d95eda69955f709d1eb,['5eb0e4b7b6c3bb0006eeb1e5'],5e9e4502f5090995de566f86,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",4,2008-09-28T23:15:00.000Z
4,5e9d0d95eda69955f709d1eb,['5eb0e4b7b6c3bb0006eeb1e6'],5e9e4502f5090995de566f86,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",5,2009-07-13T03:35:00.000Z

In [189]:
# Visualizamos los datos 
print(df.dtypes)

#Vemos que hay tipo object, verificamos sin son texto o no
print(df['rocket'].apply(type).value_counts())
print('\n')
print(df['payloads'].apply(type).value_counts())
print('\n')
print(df['launchpad'].apply(type).value_counts())
print('\n')
print(df['cores'].apply(type).value_counts())
print('\n')
print(df['date_utc'].apply(type).value_counts())

rocket           object
payloads         object
launchpad        object
cores            object
flight_number     int64
date_utc         object
dtype: object
rocket
<class 'str'>    107
Name: count, dtype: int64


payloads
<class 'str'>    107
Name: count, dtype: int64


launchpad
<class 'str'>    107
Name: count, dtype: int64


cores
<class 'str'>    107
Name: count, dtype: int64


date_utc
<class 'str'>    107
Name: count, dtype: int64

In [190]:
import ast

# # Convierte strings a listas reales
df['cores'] = df['cores'].apply(ast.literal_eval)
df['payloads'] = df['payloads'].apply(ast.literal_eval)

# print(df['cores'].apply(type).value_counts())

In [191]:
#en la columna cores, en una fila almacena distintas listas, solo deseamos quedarnos con la primera

# Para quedarnos con la primera lista 
#Corees y payloads posee varias listas dentro de una row
df = df[df['cores'].map(len) == 1]
df = df[df['payloads'].map(len) == 1]

# Dado que cores y payloads son listas de diccionarios, extraemos el primer elemento 
df['cores'] = df['cores'].map(lambda x :x[0])
df['payloads'] = df['payloads'].map(lambda x :x[0])